"""Tests for ctx.generator — core generation engine."""

from __future__ import annotations

import shutil
from pathlib import Path

from ctx.config import Config
from ctx.generator import (
    check_stale_dirs,
    format_binary_info,
    generate_tree,
    get_status,
    inspect_directory_health,
    is_binary_file,
    update_tree,
    validate_manifest_body,
)
from ctx.hasher import hash_directory
from ctx.ignore import load_ignore_patterns
from ctx.llm import FileSummary, LLMResult, SubdirSummary
from ctx.manifest import read_manifest, write_manifest


class FakeLLMClient:
    model = "fake-llm-model"

    def __init__(self) -> None:
        self.file_calls: list[tuple[Path, list[dict]]] = []
        self.directory_calls: list[tuple[Path, list[FileSummary], list[SubdirSummary]]] = []

    def summarize_files(self, dir_path: Path, files: list[dict]) -> list[LLMResult]:
        self.file_calls.append((dir_path, files))
        return [
            LLMResult(
                text=f"Summary for {f['name']}",
                input_tokens=5 if index == 0 else 0,
                output_tokens=2 if index == 0 else 0,
            )
            for index, f in enumerate(files)
        ]

    def summarize_directory(
        self,
        dir_path: Path,
        file_summaries: list[FileSummary],
        subdir_summaries: list[SubdirSummary],
    ) -> LLMResult:
        self.directory_calls.append((dir_path, file_summaries, subdir_summaries))

        body_lines = [
            f"# {dir_path.as_posix()}",
            "",
            f"Summary for {dir_path.name}.",
            "",
            "## Files",
        ]
        if file_summaries:
            body_lines.extend(f"- **{summary.name}** — {summary.summary}" for summary in file_summaries)
        else:
            body_lines.append("- None")

        body_lines.extend(["", "## Subdirectories"])
        if subdir_summaries:
            body_lines.extend(f"- **{summary.name}/** — {summary.summary}" for summary in subdir_summaries)
        else:
            body_lines.append("- None")

        body_lines.extend(["", "## Notes", "- Generated by FakeLLMClient"])
        return LLMResult(text="\n".join(body_lines) + "\n", input_tokens=7, output_tokens=3)


def _copy_sample_project(tmp_path) -> Path:
    source = Path(__file__).parent / "fixtures" / "sample_project"
    destination = tmp_path / "sample_project"
    shutil.copytree(source, destination)
    return destination


def test_is_binary_file_text(tmp_path) -> None:
    for name in ("main.py", "README.md", "notes.txt"):
        path = tmp_path / name
        path.write_text("plain text\n", encoding="utf-8")
        assert is_binary_file(path) is False


def test_is_binary_file_binary(tmp_path) -> None:
    for name in ("image.png", "program.exe", "sheet.xlsx"):
        path = tmp_path / name
        path.write_bytes(b"\x00\x01\xffbinary")
        assert is_binary_file(path) is True


def test_is_binary_file_handles_utf8_multibyte_boundary(tmp_path) -> None:
    path = tmp_path / "boundary.ts"
    path.write_bytes((b"a" * 8191) + "é".encode("utf-8"))

    assert is_binary_file(path) is False


def test_format_binary_info(tmp_path) -> None:
    spreadsheet = tmp_path / "report.xlsx"
    spreadsheet.write_bytes(b"x" * 512)
    unknown = tmp_path / "blob"
    unknown.write_bytes(b"x" * (2 * 1024 * 1024))

    assert format_binary_info(spreadsheet) == "[binary: xlsx, 1KB]"
    assert format_binary_info(unknown) == "[binary: unknown, 2MB]"


def test_generate_tree_creates_manifests(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    client = FakeLLMClient()
    stats = generate_tree(root, Config(api_key="test-key"), client, spec)

    assert stats.dirs_processed == 3
    assert stats.files_processed == 4
    assert stats.files_binary == 0
    assert stats.tokens_used == 51
    assert stats.errors == []

    for directory in (root, root / "docs", root / "src"):
        manifest = read_manifest(directory)
        assert manifest is not None
        assert manifest.frontmatter.model == "fake-llm-model"
        assert manifest.body.startswith(f"# {directory.as_posix()}")


def test_generate_tree_renders_manifest_sections_deterministically(tmp_path) -> None:
    class HallucinatingLLMClient(FakeLLMClient):
        def summarize_directory(
            self,
            dir_path: Path,
            file_summaries: list[FileSummary],
            subdir_summaries: list[SubdirSummary],
        ) -> LLMResult:
            self.directory_calls.append((dir_path, file_summaries, subdir_summaries))
            body = "\n".join(
                [
                    f"# {dir_path.as_posix()}",
                    "",
                    "Purpose inferred from real summaries.",
                    "",
                    "## Files",
                    "- **hallucinated.py** — Does not exist",
                    "- None",
                    "",
                    "## Subdirectories",
                    "- **ghost/** — Does not exist",
                    "",
                    "## Notes",
                    "- Keep summaries grounded in the real tree",
                ]
            )
            return LLMResult(text=body, input_tokens=7, output_tokens=3)

    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    generate_tree(root, Config(api_key="test-key"), HallucinatingLLMClient(), spec)

    manifest = read_manifest(root)
    assert manifest is not None
    assert "- **README.md** — Summary for README.md" in manifest.body
    assert "- **docs/** — Purpose inferred from real summaries." in manifest.body
    assert "- **src/** — Purpose inferred from real summaries." in manifest.body
    assert "hallucinated.py" not in manifest.body
    assert "ghost/" not in manifest.body
    assert "- None" not in manifest.body
    assert "- Keep summaries grounded in the real tree" in manifest.body


def test_generate_tree_bottom_up(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    client = FakeLLMClient()

    generate_tree(root, Config(api_key="test-key"), client, spec)

    call_order = [path.relative_to(root).as_posix() or "." for path, _files, _subdirs in client.directory_calls]
    # Siblings at the same depth may complete in any order (parallel), but the root must be last.
    assert set(call_order[:-1]) == {"docs", "src"}
    assert call_order[-1] == "."

    root_call = client.directory_calls[-1]
    assert [(summary.name, summary.summary) for summary in root_call[2]] == [
        ("docs", "Summary for docs."),
        ("src", "Summary for src."),
    ]


def test_update_tree_skips_fresh(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    generate_tree(root, Config(api_key="test-key"), FakeLLMClient(), spec)

    client = FakeLLMClient()
    stats = update_tree(root, Config(api_key="test-key"), client, spec)

    assert stats.dirs_processed == 0
    assert stats.dirs_skipped == 3
    assert client.file_calls == []
    assert client.directory_calls == []


def test_update_tree_regenerates_stale(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    generate_tree(root, Config(api_key="test-key"), FakeLLMClient(), spec)

    (root / "src" / "utils.py").write_text(
        '"""Utility functions for string formatting and math."""\n\n\ndef new_helper() -> int:\n    return 42\n',
        encoding="utf-8",
    )

    client = FakeLLMClient()
    stats = update_tree(root, Config(api_key="test-key"), client, spec)

    assert stats.dirs_processed == 2
    assert stats.dirs_skipped == 1
    assert [path.relative_to(root).as_posix() or "." for path, _files, _subdirs in client.directory_calls] == [
        "src",
        ".",
    ]


def test_get_status(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    generate_tree(root, Config(api_key="test-key"), FakeLLMClient(), spec)

    (root / "docs" / "CONTEXT.md").unlink()
    (root / "src" / "utils.py").write_text(
        '"""Utility functions for string formatting and math."""\n\n\ndef calculate_total(numbers: list[int]) -> int:\n    return sum(numbers) + 1\n',
        encoding="utf-8",
    )

    statuses = get_status(root, spec, root)

    assert statuses == [
        {"path": ".", "status": "stale"},
        {"path": "docs", "status": "missing"},
        {"path": "src", "status": "stale"},
    ]


def test_get_status_marks_invalid_manifest_stale(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    generate_tree(root, Config(api_key="test-key"), FakeLLMClient(), spec)

    (root / "docs" / "CONTEXT.md").write_text("not valid frontmatter", encoding="utf-8")

    statuses = get_status(root, spec, root)

    assert statuses == [
        {"path": ".", "status": "fresh"},
        {"path": "docs", "status": "stale"},
        {"path": "src", "status": "fresh"},
    ]


def test_inspect_directory_health_reports_tokens_and_errors(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    generate_tree(root, Config(api_key="test-key"), FakeLLMClient(), spec)

    (root / "docs" / "CONTEXT.md").write_text("not valid frontmatter", encoding="utf-8")

    health_entries = inspect_directory_health(root, spec, root)
    docs_entry = next(entry for entry in health_entries if entry.relative_path == "docs")
    root_entry = next(entry for entry in health_entries if entry.relative_path == ".")

    assert docs_entry.status == "stale"
    assert docs_entry.error is not None
    assert root_entry.status == "fresh"
    assert root_entry.tokens_total is not None
    assert root_entry.tokens_total > 0


def test_generate_tree_stops_at_token_budget(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    client = FakeLLMClient()
    config = Config(api_key="test-key", token_budget=1)

    stats = generate_tree(root, config, client, spec)

    # First dir should process (budget checked before each dir), then budget exceeded
    assert stats.dirs_processed >= 1
    assert stats.dirs_processed < 3
    assert stats.budget_exhausted


def test_budget_exhausted_false_when_budget_not_reached(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    client = FakeLLMClient()
    config = Config(api_key="test-key", token_budget=999_999)

    stats = generate_tree(root, config, client, spec)

    assert not stats.budget_exhausted


def test_check_stale_dirs_returns_all_when_no_manifests(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    # Remove any pre-existing CONTEXT.md files
    for ctx_file in root.rglob("CONTEXT.md"):
        ctx_file.unlink()
    spec = load_ignore_patterns(root)
    config = Config(api_key="test-key")

    stale = check_stale_dirs(root, config, spec)

    # All dirs are stale when no CONTEXT.md files exist
    assert len(stale) > 0
    assert root in stale


def test_check_stale_dirs_returns_empty_after_full_generate(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    config = Config(api_key="test-key")
    generate_tree(root, config, FakeLLMClient(), spec)

    stale = check_stale_dirs(root, config, spec)

    assert stale == []


def test_check_stale_dirs_respects_changed_files_filter(tmp_path) -> None:
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    config = Config(api_key="test-key")
    generate_tree(root, config, FakeLLMClient(), spec)

    # Modify a file in the docs dir
    (root / "docs" / "guide.md").write_text("updated", encoding="utf-8")

    stale = check_stale_dirs(root, config, spec, changed_files=[root / "docs" / "guide.md"])

    # Only docs and root (ancestor) should be stale, not src
    stale_names = {d.name for d in stale}
    assert "docs" in stale_names or "." in stale_names  # docs or root
    assert "src" not in stale_names


def test_validate_manifest_body_reports_hallucinations_and_illegal_none(tmp_path) -> None:
    root = tmp_path / "project"
    root.mkdir()
    (root / "real.py").write_text("print('hi')\n", encoding="utf-8")
    (root / "pkg").mkdir()
    spec = load_ignore_patterns(root)
    body = "\n".join(
        [
            f"# {root.as_posix()}",
            "",
            "Project root.",
            "",
            "## Files",
            "- **real.py** — Real file",
            "- **fake.py** — Hallucinated file",
            "",
            "## Subdirectories",
            "- **pkg** — Missing slash",
            "",
            "## Notes",
            "- None",
            "- Helpful note",
            "",
        ]
    )
    write_manifest(
        root,
        model="test-model",
        content_hash=hash_directory(root, spec, root),
        files=1,
        dirs=1,
        tokens_total=10,
        body=body,
    )

    manifest = read_manifest(root)
    assert manifest is not None

    issues = validate_manifest_body(root, root, spec, manifest)

    assert any("Files section lists nonexistent entries: fake.py" in issue for issue in issues)
    assert any("Subdirectories entry is missing a trailing slash: pkg" in issue for issue in issues)
    assert any("Notes section contains an illegal None row." in issue for issue in issues)


def test_mid_level_budget_enforcement(tmp_path) -> None:
    """Budget should be enforced within a depth level, not just between levels."""
    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    # Budget of 1 — first directory at the deepest level will use tokens,
    # then remaining directories at the same level should be skipped.
    config = Config(api_key="test-key", token_budget=1)
    client = FakeLLMClient()

    stats = generate_tree(root, config, client, spec)

    assert stats.budget_exhausted
    # At least one dir should be processed (the first one at the deepest level)
    assert stats.dirs_processed >= 1
    # But not all dirs should complete
    assert stats.dirs_processed < 3


def test_configurable_max_concurrent_dirs(tmp_path) -> None:
    """max_concurrent_dirs config should be respected."""
    from ctx.config import LOCAL_PROVIDERS
    from ctx.generator import _DEFAULT_CLOUD_PARALLEL_DIRS, _DEFAULT_LOCAL_PARALLEL_DIRS

    # Verify defaults exist
    assert _DEFAULT_CLOUD_PARALLEL_DIRS == 1
    assert _DEFAULT_LOCAL_PARALLEL_DIRS == 4

    root = _copy_sample_project(tmp_path)
    spec = load_ignore_patterns(root)
    config = Config(api_key="test-key", max_concurrent_dirs=2)
    client = FakeLLMClient()

    stats = generate_tree(root, config, client, spec)

    # Should still complete all dirs, just with limited parallelism
    assert stats.dirs_processed == 3
    assert stats.errors == []
