#!/usr/bin/env sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "🚨 ERROR: Direct pushes to the 'main' or 'master' branch are forbidden."
  echo "All changes must go through a Pull Request."
  exit 1
fi
